#include "Building/BuildingAssistComponent.h"

#include "Building/Component/BuildingPreviewComponent.h"
#include "Building/BaseBuilding.h"
#include "Building/Component/BuildingProgress.h"
#include "Building/Widget/BuildingInfoWidget.h"

#include "Engine/StaticMeshActor.h"
#include "Engine/DataTable.h"
#include "GameFramework/Pawn.h"

#include "Kismet/GameplayStatics.h"
#include "Kismet/KismetMathLibrary.h"
#include "Kismet/KismetSystemLibrary.h"

#include "LandscapeProxy.h"
#include "Blueprint/UserWidget.h"

UBuildingAssistComponent::UBuildingAssistComponent()
{
	PrimaryComponentTick.bCanEverTick = true;

	// ОШГЛ РЇСЌ
	static ConstructorHelpers::FClassFinder<UUserWidget> BuildingWidget(
		TEXT("/Game/Building/Widget/WBP_BuildGuidInfo.WBP_BuildGuidInfo_C"));
	if (BuildingWidget.Succeeded())
	{
		BuildingInfoClass = BuildingWidget.Class;
	}

	// БтКЛ КєЕљ Actor ХЌЗЁНК
	static ConstructorHelpers::FClassFinder<ABaseBuilding> BuildingBP(
		TEXT("/Game/Building/Blueprints/Test/Bp_BuildingActor.Bp_BuildingActor_C"));
	if (BuildingBP.Succeeded())
	{
		BuildingClass = BuildingBP.Class;
	}

	// Snap DataTable ЗЮЕљ
	static ConstructorHelpers::FObjectFinder<UDataTable> MeshData(
		TEXT("/Game/Building/Data/DT_SnapData.DT_SnapData"));
	if (MeshData.Succeeded())
	{
		if (UDataTable* DataTable = MeshData.Object)
		{
			DataTable->GetAllRows<FSnapRule>(TEXT("SnapData"), SnapDataRows);
		}
	}

	// TraceПы ObjectTypes
	buildPointObjectTypes.Add(UEngineTypes::ConvertToObjectType(ECC_WorldStatic));
	buildPointObjectTypes.Add(UEngineTypes::ConvertToObjectType(ECC_WorldDynamic));
	EndBuilding();
}

void UBuildingAssistComponent::BeginPlay()
{
	UActorComponent::BeginPlay();

	if (GetOwner())
	{
		ownerPawn = Cast<APawn>(GetOwner());
	}

	if (ownerPawn.IsValid())
	{
		// ЧСИЎКф ФФЦїГЭЦЎ Л§МК
		buildingPreviewActor = Cast<UBuildingPreviewComponent>(
			ownerPawn->AddComponentByClass(UBuildingPreviewComponent::StaticClass(), false, FTransform::Identity, false));

		if (buildingPreviewActor)
		{
			buildingPreviewActor->SetRelativeLocation(FVector(400.f, 0.f, 0.f));
		}
	}

	// Trace Ignore: МвРЏРк
	buildPointIgnore.Add(GetOwner());

	// КєЕљ ОШГЛ РЇСЌ Л§МК
	if (BuildingInfoClass)
	{
		BuildingInfo = Cast<UBuildingInfoWidget>(CreateWidget(GetWorld(), BuildingInfoClass));
	}
}

void UBuildingAssistComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	UActorComponent::TickComponent(DeltaTime, TickType, ThisTickFunction);

	canBuilding = false;

	if (!buildingActive || !ownerPawn.IsValid() || !buildingPreviewActor)
	{
		return;
	}

	// ФЋИоЖѓ Trace + НКГР + Preview РЬЕП
	if (UpdatePreview())
	{
		// PreviewComponent АЁ OnUpdateTransform ПЁМ­ АуФЇ ЦЧСЄРЛ ГЁГТДйАэ АЁСЄ
		canBuilding = buildingPreviewActor->IsBuildable();
	}
	else
		canBuilding = false;
}

void UBuildingAssistComponent::SetBuildingStaticMesh(UStaticMesh* NewStaticMesh)
{
	if (!NewStaticMesh || !buildingPreviewActor)
	{
		return;
	}

	BuildingMesh = NewStaticMesh;
	buildingPreviewActor->SetBuildingMsh(BuildingMesh.Get());

	BottomTrans = buildingPreviewActor->GetSocketTransform(TEXT("Bottom"), ERelativeTransformSpace::RTS_Component);
	// ЧіРч ChildMesh ПЁ ИТДТ SnapRuleЕщИИ УпЗСЕв
	SnapRulesForChild.Reset();
	for (FSnapRule* Row : SnapDataRows)
	{
		if (Row && Row->ChildMesh == BuildingMesh.Get())
		{
			SnapRulesForChild.Add(Row);
		}
	}
}

void UBuildingAssistComponent::StartBuilding()
{
	OnOffAssist(true);

	if (BuildingInfo)
	{
		BuildingInfo->AddToViewport();
	}

	if (buildingPreviewActor)
	{
		buildingPreviewActor->StartPreView();
	}
}

void UBuildingAssistComponent::EndBuilding()
{
	OnOffAssist(false);

	if (BuildingInfo)
	{
		BuildingInfo->RemoveFromParent();
	}

	if (buildingPreviewActor)
	{
		buildingPreviewActor->EndPreView();
	}
}

void UBuildingAssistComponent::SpawnBuilding()
{
	if (!buildingActive || !canBuilding || !BuildingClass || !buildingPreviewActor || !BuildingMesh.IsValid())
	{
		return;
	}

	FActorSpawnParameters Param;
	Param.Instigator = ownerPawn.Get();
	Param.Owner = ownerPawn.Get();
	Param.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;
	FTransform SpawnTransform{};
	SpawnTransform .SetLocation(buildingPreviewActor->GetComponentLocation());
	SpawnTransform .SetRotation(buildingPreviewActor->GetComponentRotation().Quaternion());
	SpawnTransform .SetScale3D(buildingPreviewActor->GetComponentScale());

	ABaseBuilding* Building = GetWorld()->SpawnActor<ABaseBuilding>(BuildingClass, SpawnTransform, Param);
	if (Building)
	{
		if (UBuildingProgress* Progress = Building->GetBuildingProgress())
		{
			Progress->SetbuildingMesh(BuildingMesh.Get());
		}
	}

	// ЧСИЎКф ШИРќ УЪБтШ­
	buildingPreviewActor->SetWorldRotation(FQuat::Identity);
}

void UBuildingAssistComponent::RotateBuilding(float AddYaw)
{
	if (buildingPreviewActor)
	{
		buildingPreviewActor->AddWorldRotation(FRotator(0.f, AddYaw, 0.f));
		YawRotation = UKismetMathLibrary::NormalizeAxis(YawRotation + AddYaw);
	}
}

void UBuildingAssistComponent::OnOffAssist(bool bValue)
{
	buildingActive = bValue;
	canBuilding = !bValue;
	SetComponentTickEnabled(bValue);

	if (!buildingPreviewActor)
	{
		return;
	}

	if (bValue)
	{
		buildingPreviewActor->StartPreView();
	}
	else
	{
		buildingPreviewActor->EndPreView();
	}
}

bool UBuildingAssistComponent::UpdatePreview()
{
	if (!ownerPawn.IsValid() || !buildingPreviewActor)
	{
		return false;
	}

	const APlayerCameraManager* CameraManager = UGameplayStatics::GetPlayerCameraManager(GetWorld(), 0);
	if (!CameraManager)
	{
		return false;
	}

	const FVector CamLocation = CameraManager->GetCameraLocation();
	const FRotator CamRotation = CameraManager->GetCameraRotation();
	const FVector TraceStart = CamLocation;
	const FVector TraceEnd = CamLocation + CamRotation.Vector() * 1200.f - BottomTrans.GetLocation();

	FHitResult HitResult;
	bool bHit = UKismetSystemLibrary::LineTraceSingleForObjects(
		GetWorld(),
		TraceStart,
		TraceEnd,
		buildPointObjectTypes,
		true,
		buildPointIgnore,
		EDrawDebugTrace::Type::None,
		HitResult,
		true);

	FTransform PreviewWorld = buildingPreviewActor->GetComponentTransform();

	// БтКЛ ШИРќРК БтСИ ЧСИЎКфРЧ ШИРќ РЏСі (RotateBuildingРИЗЮ СЖР§)
	FRotator  CurrentRot = PreviewWorld.GetRotation().Rotator();
	//FRotator TO FQUAT
	CurrentRot.Yaw = YawRotation;
	FVector CurrentScale = FVector::OneVector;

	if (!bHit) // no hit
	{
		// ОЦЙЋ АЭЕЕ ИТСі ОЪРИИщ TraceEndПЁ РкРЏ ЙшФЁ
		PreviewWorld.SetLocation(TraceEnd);
		PreviewWorld.SetRotation(CurrentRot.Quaternion());
		PreviewWorld.SetScale3D(CurrentScale);

		buildingPreviewActor->SetWorldTransform(PreviewWorld, false, nullptr, ETeleportType::TeleportPhysics);
		return true;
	}
	// HitЕШ ActorПЁМ­ ParentMesh УЃБт
	UStaticMeshComponent* ParentMeshComp = nullptr;
	if (AActor* HitActor = HitResult.GetActor())
	{
		for (UActorComponent* Comp : HitActor->GetComponents())
		{
			if (UStaticMeshComponent* SMC = Cast<UStaticMeshComponent>(Comp))
			{
				if (SMC != buildingPreviewActor)
				{
					ParentMeshComp = SMC;
					break;
				}
			}
		}
	}
	const FVector ImpactPoint = HitResult.ImpactPoint - BottomTrans.GetLocation();

	// ParentMeshАЁ ОјРИИщ ImpactPointПЁ РкРЏ ЙшФЁ
	if (!ParentMeshComp || !BuildingMesh.IsValid() || SnapRulesForChild.Num() == 0) // NotSnap, hitPosition
	{
		PreviewWorld.SetLocation(ImpactPoint);
		PreviewWorld.SetRotation(CurrentRot.Quaternion());
		PreviewWorld.SetScale3D(CurrentScale);

		buildingPreviewActor->SetWorldTransform(PreviewWorld, false, nullptr, ETeleportType::TeleportPhysics);
		return true;
	}

	// Parent StaticMesh БтСиРИЗЮ НКГР Зъ ЧЪХЭИЕ
	UStaticMesh* ParentStaticMesh = ParentMeshComp->GetStaticMesh();
	if (!ParentStaticMesh) 
	{
		PreviewWorld.SetLocation(ImpactPoint);
		PreviewWorld.SetRotation(CurrentRot.Quaternion());
		PreviewWorld.SetScale3D(CurrentScale);

		buildingPreviewActor->SetWorldTransform(PreviewWorld, false, nullptr, ETeleportType::TeleportPhysics);
		return true;
	}

	const FSnapRule* MainRule{};
	for (const FSnapRule* Rule : SnapRulesForChild)
	{
		if (Rule && Rule->ParentMesh == ParentStaticMesh)
		{
			MainRule = Rule;
			break;
		}
	}

	// РЬ ParentПЁ ДыЧб НКГР ЗъРЬ ОјРИИщ ImpactPointПЁ РкРЏ ЙшФЁ
	if (!MainRule) // !Snaped
	{
		PreviewWorld.SetLocation(ImpactPoint);
		PreviewWorld.SetRotation(CurrentRot.Quaternion());
		PreviewWorld.SetScale3D(CurrentScale);

		buildingPreviewActor->SetWorldTransform(PreviewWorld, false, nullptr, ETeleportType::TeleportPhysics);
		return true;
	}

	// АЁРх АЁБюПю ParentAnchorWorld УЃБт
	const FTransform ParentWorld = ParentMeshComp->GetComponentTransform();

	const float SnapDistSq = SnapDistance * SnapDistance;
	const FSnapRule* BestRule = nullptr;
	int Index{};
	int BestIndex{};
	float BestDistSq = TNumericLimits<float>::Max();
	FTransform BestParentAnchorWorld;
	float Min = TNumericLimits<float>::Max();
	//FString Temp{};
	for (const FSnapAnchorData& Data : MainRule->ArrayAnchors)
	{
		FTransform ParentAnchorWorld = MainRule->ParentAnchorLocal * ParentWorld;
		FVector AnchorWorldPos = ParentAnchorWorld.GetLocation();
		FVector PreviewLocation = ImpactPoint;

		if (Data.ParentAnchor != ESnapAnchor::NONE)
		{
			FVector ParentOffset = FSnapRule::AnchorToOffset(Data.ParentAnchor, MainRule->ParentMesh->GetBoundingBox().GetSize()); // FVector(1, -1, 1)
			FVector ChildOffset = FSnapRule::AnchorToOffset(Data.ChildAnchor, MainRule->ChildMesh->GetBoundingBox().GetSize()) + Data.ChildOffset;

			ParentAnchorWorld = HitResult.GetActor()->GetTransform();
			AnchorWorldPos = ParentAnchorWorld.TransformPosition(ParentOffset);
			const FVector RotatedChildAnchor = ParentAnchorWorld.GetRotation() * ChildOffset;
			PreviewLocation = AnchorWorldPos - RotatedChildAnchor;

		}

		const float DistSq = FVector::DistSquared(ImpactPoint, AnchorWorldPos);
		const float dot = FVector::DotProduct((PreviewLocation - AnchorWorldPos).GetSafeNormal(), (GetOwner()->GetActorLocation() - AnchorWorldPos).GetSafeNormal());
		if (FMath::IsNearlyEqual(DistSq, BestDistSq))
		{
			if (dot > Min)
			{
				BestDistSq = DistSq;
				BestRule = MainRule;
				BestParentAnchorWorld = ParentAnchorWorld;
				BestIndex = Index;
				Min = dot;
			}
		}
		else if (DistSq < BestDistSq )
		{
			BestDistSq = DistSq;
			BestRule = MainRule;
			BestParentAnchorWorld = ParentAnchorWorld;
			BestIndex = Index;
			Min = dot;
		}
	
		Index++;
	}
	//UE_LOG(LogTemp, Warning, TEXT("%s"),  *Temp);

	// AnchorАЁ ГЪЙЋ ИжИщ НКГРЧЯСі ОЪАэ ImpactPointЗЮ РкРЏ ЙшФЁ
	if (!BestRule || BestDistSq > SnapDistSq)
	{
		PreviewWorld.SetLocation(ImpactPoint);
		PreviewWorld.SetRotation(CurrentRot.Quaternion());
		PreviewWorld.SetScale3D(CurrentScale);

		buildingPreviewActor->SetWorldTransform(PreviewWorld, false, nullptr, ETeleportType::TeleportPhysics);
		return true;
	}
	if (BestRule->ArrayAnchors.IsValidIndex(BestIndex))
	{
		CurrentScale = BestParentAnchorWorld.GetScale3D();
		const FSnapAnchorData& Data = BestRule->ArrayAnchors[BestIndex];
		FVector ParentOffset = FSnapRule::AnchorToOffset(Data.ParentAnchor, MainRule->ParentMesh->GetBoundingBox().GetSize());;
		FVector ChildOffset = FSnapRule::AnchorToOffset(Data.ChildAnchor, MainRule->ChildMesh->GetBoundingBox().GetSize()) + Data.ChildOffset;

		// ШИРќ ЦїЧд Parent Anchor World СТЧЅ
		const FVector ParentAnchorWorld = BestParentAnchorWorld.TransformPosition(ParentOffset * CurrentScale);

		// ШИРќ КИСЄ: ChildAnchorLocalРЛ Parent БтСиРИЗЮ ШИРќ
		const FVector RotatedChildAnchor = BestParentAnchorWorld.GetRotation() * (ChildOffset * CurrentScale);

		// УжСО РЇФЁ = ParentAnchorWorld - (ШИРќЕШ ChildAnchorLocal)
		//const FVector ChildWorldPos = ParentAnchorWorld - RotatedChildAnchor;

		PreviewWorld.SetLocation(ParentAnchorWorld - RotatedChildAnchor);

		CurrentRot = BestParentAnchorWorld.GetRotation().Rotator();
		CurrentRot.Yaw += FSnapRule::AnchorYaw(Data.ChildYaw);
		PreviewWorld.SetRotation(CurrentRot.Quaternion());
		PreviewWorld.SetScale3D(CurrentScale);
	}
	else
	{
		// НКГР: ChildWorld * ChildAnchorLocal = ParentAnchorWorld
		const FTransform& ChildAnchorLocal = BestRule->ChildAnchorLocal;

		const FQuat ParentAnchorWorldRot = BestParentAnchorWorld.GetRotation();
		const FQuat ChildAnchorLocalRot = ChildAnchorLocal.GetRotation();

		const FQuat ChildWorldRot = ParentAnchorWorldRot * ChildAnchorLocalRot.Inverse();

		const FVector ParentAnchorWorldPos = BestParentAnchorWorld.GetLocation();
		const FVector ChildAnchorLocalPos = ChildAnchorLocal.GetLocation();

		const FVector ChildAnchorWorldOffset = ChildWorldRot.RotateVector(ChildAnchorLocalPos);
		const FVector ChildWorldPos = ParentAnchorWorldPos - ChildAnchorWorldOffset;

		PreviewWorld.SetLocation(ChildWorldPos);
		PreviewWorld.SetRotation(ChildWorldRot);
		PreviewWorld.SetScale3D(CurrentScale);
	}

	buildingPreviewActor->SetWorldTransform(PreviewWorld, false, nullptr, ETeleportType::ResetPhysics);
	return true;
}
